name: Upload helm package
description: Upload the helm package
inputs:
  registry-username:
    description: Username for the OCI registry
    required: true
  registry-password:
    description: Password for the OCI registry
    required: true
  registry-url:
    description: URL for the OCI registry
    required: true
    default: "registry.hub.docker.com"
  registry-repository:
    description: Repository in the OCI registry
    required: true
    default: "dynatrace"
  helm-package-url:
    description: URL for the helm package
    required: true
    default: docker.io/gabrielkrenn390/dynatrace-operator
  version:
    description: The version of the helm package to upload
    required: true
  version-without-prefix:
    description: The version of the helm package to upload without the leading 'v' character
    required: true

runs:
  using: "composite"
  steps:
  - name: Upload helm package to OCI registry
    id: push-helm-to-OCI
    shell: bash
    run: |
      helm registry login -u "${{ inputs.registry-username }}" -p "${{ inputs.registry-password }}" "${{ inputs.registry-url }}"
      hack/build/ci/push-helm-chart.sh \
        "./helm-pkg/dynatrace-operator-${{ inputs.version-without-prefix }}.tgz" \
        "oci://${{ inputs.registry-url }}/${{ inputs.registry-repository }}"
  - name: Login to Registry
    uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
    with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
  - name: Sign OCI package with cosign
    uses: ./.github/actions/sign-image
    with:
      image: "{{ inputs.helm-package-url }}:${{ inputs.version }}@${{ steps.push-helm-to-OCI.outputs.digest }}"
      signing-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      signing-password: ${{ secrets.COSIGN_PASSWORD }}
