name: Build Helm packages
description: Builds the helm packages
inputs:
  version:
    description: The version of the operator that should be deployed
    required: true
  github-token:
    description: Token used to fetch the current helm version
    required: true
  secring:
    description: Contains the private key that is used to sign the helm packages
    required: true
  passphrase:
    description: Passphrase used to encrypt the private key
    required: true
  output-dir:
    description: Directory where built package should be put
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        token: ${{ inputs.github-token }}
    - name: Generate helm-package
      shell: bash
      run: |
        mkdir -p ~/.gnupg
        echo "${{ inputs.secring }}" | base64 -d > ~/.gnupg/secring.gpg
        echo "${{ inputs.passphrase }}" > ~/.gnupg/passphrase

        cleanup() {
          rm -f ~/.gnupg/secring.gpg
          rm -f ~/.gnupg/passphrase
        }

        trap 'cleanup' ERR

        helm package \
          "./config/helm/chart/default/" \
          -d ${{ inputs.output-dir }} \
          --app-version "${{ inputs.version }}" \
          --version "${{ inputs.version }}" \
          --sign \
          --key "Dynatrace LLC" \
          --keyring ~/.gnupg/secring.gpg \
          --passphrase-file ~/.gnupg/passphrase

        mv ${{ inputs.output-dir }}/dynatrace-operator-${{ inputs.version }}.tgz ${{ inputs.output-dir }}/dynatrace-operator.tgz
        mv ${{ inputs.output-dir }}/dynatrace-operator-${{ inputs.version }}.tgz.prov ${{ inputs.output-dir }}/dynatrace-operator.tgz.prov
