name: Run e2e tests
description: Runs the e2e test in the specified environment
inputs:
  flc-namespace:
    description: The namespace FLC uses
    required: true
  flc-environment:
    description: The environment FLC uses
    required: true
  target-branch:
    description: Target branch to run E2E tests over
    required: true
    default: main
  target-image:
    description: Target image to run E2E tests over
    required: false
  helm-chart:
    description: Helm chart used for installation
    required: false
  tenant1-name:
    description: The name of Tenant 1
    required: true
  tenant1-apitoken:
    description: The API token of Tenant 1
    required: true
  tenant1-apitoken-nosettings:
    description: The API token of Tenant 1 without settings scope
    required: false
  tenant1-dataingesttoken:
    description: The data ingest token of Tenant 1
    required: true
  tenant1-oauth-client-id:
    description: The OAuth client ID of Tenant 1
    required: true
  tenant1-oauth-secret:
    description: The OAuth secret of Tenant 1
    required: true
  tenant1-oauth-urn:
    description: The OAuth urn of Tenant 1
    required: true
  tenant2-name:
    description: The name of Tenant 2
    required: true
  tenant2-apitoken:
    description: The API token of Tenant 2
    required: true
  tenant2-dataingesttoken:
    description: The data ingest token of Tenant 2
    required: true
  github-token:
    description: The GitHub token
    required: true
outputs:
  cluster_status:
    description: Status of the cluster creation ['skipped'|'success']
    value: ${{ steps.create_cluster.outputs.cluster_status }}
runs:
  using: composite
  steps:
    - name: Install make
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y make
    - name: Checkout workflow scripts from ref branch
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        path: ref
    - name: Checkout target branch
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: ${{ inputs.target-branch || 'main' }}
        path: target
    - name: Run tests
      shell: bash
      run: |
        ref/.github/scripts/run-e2e-tests.sh

