name: Run e2e tests
description: Runs the e2e test in the specified environment
outputs:
  cluster_status:
    description: Status of the cluster creation ['skipped'|'success']
    value: ${{ steps.create_cluster.outputs.cluster_status }}
runs:
  using: composite
  steps:
    - name: Checkout workflow scripts from ref branch
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        path: ref
    - name: Checkout target branch
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: main
        path: target
    - name: Run tests
      shell: bash
      run: |
        ref/.github/scripts/run-e2e-tests.sh

