name: E2E tests

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target branch to run E2E tests over'
        required: true
        default: 'main'
      helm-chart:
        description: 'Helm chart used for installation'
        required: true
        default: 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart'
        type: string

permissions:
  checks: write

jobs:
  notify-slack:
    name: Notify test results in Slack
    environment: E2E
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    steps:
      - name: Set Slack message
        id: set_slack_message
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target || 'main' }}
        run: |
          get_status() {
            if [ "$1" = "skipped" ]; then
              echo "cluster creation failed and skipped tests :large_yellow_circle:"
            elif [ "$2" = "success" ]; then
              echo "tests passed :green_heavy_check_mark:"
            else
              echo "tests failed :red_circle:"
            fi
          }

          K8S_STATUS=$(get_status "${{ needs.run-in-k8s.outputs.cluster_status }}" "${{ needs.run-in-k8s.result }}")
          OCP_STATUS=$(get_status "${{ needs.run-in-ocp.outputs.cluster_status }}" "${{ needs.run-in-ocp.result }}")
          OCP_FIPS_STATUS=$(get_status "${{ needs.run-in-ocp-fips.outputs.cluster_status }}" "${{ needs.run-in-ocp-fips.result }}")

          MESSAGE="${K8S_STATUS} on kubernetes :kubernetes:\n${OCP_STATUS} on openshift :openshift:\n${OCP_FIPS_STATUS} on FIPS openshift :lock:\nusing ${{ github.event.inputs.target || 'main' }} branch (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          
          echo "$MESSAGE"
