name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+ # include prerelease tags too

jobs:
  prepare:
    permissions:
      contents: read
      id-token: write
    name: Prepare properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Prepare build parameters
        id: prep
        run: |
          hack/build/ci/prepare-build-variables.sh
      - name: Docker metadata
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        id: meta
        with:
          images: dynatrace/dynatrace-operator
          tags: ${{ steps.prep.outputs.docker_image_tag }}
          labels: |
            ${{ steps.prep.outputs.docker_image_labels }}
            vcs-ref=${{ github.sha }}
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      version: ${{ steps.prep.outputs.docker_image_tag }}

  pre-release:
    name: Create pre-release
    needs: [prepare]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [ dockerhub ]
        include:
          - registry: dockerhub
            url: docker.io
            repository: DOCKERHUB_REPOSITORY
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Generate release notes
        id: generate_notes
        env:
          PRE_RELEASE: true
        run: |
          touch config/deploy/kubernetes/kubernetes-all.yaml
          touch config/deploy/openshift/openshift-all.yaml
      - name: Rename manifests
        run: |
          mv config/deploy/kubernetes/kubernetes-all.yaml config/deploy/kubernetes/kubernetes.yaml
          mv config/deploy/openshift/openshift-all.yaml config/deploy/openshift/openshift.yaml
          echo And the version is ${{ steps.prep.outputs.docker_image_tag }}
      - name: Build helm packages
        uses: ./.github/actions/build-helm
        with:
          version: "${{ steps.prep.outputs.docker_image_tag }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secring: ${{ secrets.SECRING }}
          passphrase: ${{ secrets.PASSPHRASE }}
          output-dir: "./helm-pkg"
      - name: Pre-release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./CHANGELOG.md
          files: |
            config/deploy/kubernetes/kubernetes.yaml
            config/deploy/openshift/openshift.yaml
            helm-pkg/dynatrace-operator.tgz
            helm-pkg/dynatrace-operator.tgz.prov
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          fail_on_unmatched_files: true
