name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+ # include prerelease tags too


jobs:
  prepare:
    permissions:
      contents: read
      id-token: write
    name: Prepare properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Prepare build parameters
        id: prep
        run: |
          hack/build/ci/prepare-build-variables.sh
      - name: Docker metadata
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        id: meta
        with:
          images: dynatrace/dynatrace-operator
          tags: ${{ steps.prep.outputs.docker_image_tag }}
          labels: |
            ${{ steps.prep.outputs.docker_image_labels }}
            vcs-ref=${{ github.sha }}
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      version: ${{ steps.prep.outputs.docker_image_tag }}
      version_without_prefix: ${{ steps.prep.outputs.docker_image_tag_without_prefix }}

  release:
    name: Create release
    needs: [prepare]
    environment: Release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Golang
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
      - name: Download dependencies
        id: depdownload
        run: |
          hack/build/ci/install-cgo-dependencies.sh
      - name: Generate release notes
        shell: bash
        env:
          PRE_RELEASE: ${{ contains(github.ref, '-rc.') }}
        run: |
          hack/build/ci/generate-release-notes.sh
      - name: Generate K8s manifests
        shell: bash
        env:
          VERSION_WITHOUT_PREFIX: ${{ needs.prepare.outputs.version_without_prefix }}
          VERSION: ${{ needs.prepare.outputs.version }}
        run: |
          make manifests/crd/release CHART_VERSION="${VERSION_WITHOUT_PREFIX}"

          make manifests/kubernetes IMAGE="docker.io/gasdslkfj/dynatrace-operator" TAG="${VERSION}"
          make manifests/openshift IMAGE="registry.connect.redhat.com/sldkfjlskdjf/dynatrace-operator" TAG="${VERSION}"
      - name: Rename manifests if pre-release
        if: ${{ contains(github.ref, '-rc.') }}
        run: |
          mv config/deploy/kubernetes/kubernetes-all.yaml config/deploy/kubernetes/kubernetes.yaml
          mv config/deploy/openshift/openshift-all.yaml config/deploy/openshift/openshift.yaml
      - name: Build helm packages
        uses: ./.github/actions/build-helm
        with:
          version_without_prefix: ${{ needs.prepare.outputs.version_without_prefix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secring: ${{ secrets.SECRING }}
          passphrase: ${{ secrets.PASSPHRASE }}
          output-dir: "./helm-pkg"
      - name: Upload and sign helm package to dockerhub
        uses: ./.github/actions/upload-helm
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          version: ${{ needs.prepare.outputs.version }}
          version-without-prefix: ${{ needs.prepare.outputs.version_without_prefix }}
          signing-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          signing-password: ${{ secrets.COSIGN_PASSWORD }}
      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        if: ${{ contains(github.ref, '-rc.') }}
        with:
          body_path: ./CHANGELOG.md
          files: |
            config/deploy/kubernetes/kubernetes.yaml
            config/deploy/openshift/openshift.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          fail_on_unmatched_files: true
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ !contains(github.ref, '-rc.') }}
        with:
          body_path: ./CHANGELOG.md
          files: |
            config/deploy/kubernetes/kubernetes.yaml
            config/deploy/kubernetes/kubernetes-csi.yaml
            config/deploy/kubernetes/gke-autopilot.yaml
            config/deploy/openshift/openshift.yaml
            config/deploy/openshift/openshift-csi.yaml
            helm-pkg/dynatrace-operator-${{ needs.prepare.outputs.version_without_prefix }}.tgz
            helm-pkg/dynatrace-operator-${{ needs.prepare.outputs.version_without_prefix }}.tgz.prov
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          fail_on_unmatched_files: true
